# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-24 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(default='default.png', upload_to='profiles/')),
                ('bio', tinymce.models.HTMLField(default='Rate', max_length=500)),
                ('website', url_or_relative_url_field.fields.URLOrRelativeURLField()),
                ('phone_number', models.CharField(default=788494207, max_length=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
