# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-25 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awardapp', '0002_auto_20191025_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('usability', models.IntegerField(default=0)),
                ('content', models.IntegerField(default=0)),
                ('design', models.IntegerField(default=0)),
                ('link', url_or_relative_url_field.fields.URLOrRelativeURLField(max_length=400)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image_landing', models.ImageField(upload_to='landing/')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
